name: qaq
services:
  gateway-api:
    image: blacklee123/gateway-api
    restart: always
    volumes:
      - ./gateway-api/application.yaml:/app/application.yaml
    environment:
      - MYSQL_SERVER=${MYSQL_SERVER:?error}
      - MYSQL_PORT=${MYSQL_PORT:?error}
      - MYSQL_USER=${MYSQL_USER:?error}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?error}
      - RSA_PUBLICKEY=${RSA_PUBLICKEY:?error}
  uniauth-api:
    image: blacklee123/uniauth-api
    restart: always
    volumes:
      - ./uniauth-api/application.yaml:/app/application.yaml
    environment:
      - MYSQL_SERVER=${MYSQL_SERVER:?error}
      - MYSQL_PORT=${MYSQL_PORT:?error}
      - MYSQL_USER=${MYSQL_USER:?error}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?error}
      - FEISHU_APP_ID=${FEISHU_APP_ID:?error}
      - FEISHU_APP_SECRET=${FEISHU_APP_SECRET:?error}
      - FEISHU_ENCRYPT_KEY=${FEISHU_ENCRYPT_KEY:?error}
      - FEISHU_VERIFICATION_TOKEN=${FEISHU_VERIFICATION_TOKEN:?error}
      - RSA_PRIVATEKEY=${RSA_PRIVATEKEY:?error}
      - QAQ_ADMIN=${QAQ_ADMIN:?error}
      - QAQ_HOST=${QAQ_HOST:?error}
  uniauth-web:
    image: blacklee123/uniauth-web
    restart: always
    volumes:
      - ./uniauth-web/default.conf:/etc/nginx/conf.d/default.conf
      - ./uniauth-web/env.js:/usr/share/nginx/html/env.js
      - ./uniauth-web/navbar.json:/usr/share/nginx/html/navbar.json
  docs:
    image: blacklee123/docs
    restart: always
    volumes:
      - ./docs/default.conf:/etc/nginx/conf.d/default.conf
  upload:
    image: blacklee123/upload
    restart: always
    command:
      - gunicorn
      - upload.wsgi:application
      - --bind=0.0.0.0:80
      - --log-level=info
      - --log-file=-
      - --access-logfile=-
      - --error-logfile=-
      - --worker-class=gevent
      - --threads=4
    environment:
      - DEBUG=${UPLOAD_DEBUG}
      - MYSQL_SERVER=${MYSQL_SERVER:?error}
      - MYSQL_PORT=${MYSQL_PORT:?error}
      - MYSQL_USER=${MYSQL_USER:?error}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?error}
      - S3_SERVER=${UPLOAD_S3_SERVER:?error}
      - S3_ACCESSKEY=${UPLOAD_S3_ACCESSKEY:?error}
      - S3_SECRET=${UPLOAD_S3_SECRET:?error}
      - S3_BUCKET=${UPLOAD_S3_BUCKET:?error}
      - S3_VENDER=${UPLOAD_S3_VENDER}
      - QAQ_HOST=${QAQ_HOST:?error}
  static:
    image: blacklee123/static
    restart: always
    environment:
      - FEISHU_APP_ID=${FEISHU_APP_ID:?error}
      - FEISHU_APP_SECRET=${FEISHU_APP_SECRET:?error}
    volumes:
      - ./static/data:/app/data
  nginx:
    image: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/ssl:/etc/nginx/ssl