server:
  port: 80
logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.qaq.gateway: INFO
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
